# Generated by Django 4.1.13 on 2024-06-06 16:55

import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('unit_purchase', models.TextField(max_length=50)),
                ('unit_measure', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('department_id', models.CharField(max_length=50)),
                ('url_picture', models.TextField(max_length=250)),
                ('location', models.TextField(max_length=250)),
                ('lot_flag', models.BooleanField()),
                ('price_lot_flag', models.BooleanField()),
                ('alert_minimum_stock_flag', models.BooleanField()),
                ('alert_expiration_flag', models.BooleanField()),
                ('comments', models.TextField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
