# Generated by Django 4.1.13 on 2024-07-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='alert_expiration_flag',
            new_name='alert_expiration_date_flag',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='last_update_date',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_purchase',
            new_name='unit_measure_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_measure',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='department_id',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_lot_flag',
            field=models.BooleanField(default=False),
        ),
    ]
